export const REQUEST_USERINFO = 'REQUEST_USERINFO'
export const RECEIVE_USERINFO = 'RECEIVE_USERINFO'

export const REQUEST_PERMISSION = 'REQUEST_PERMISSION'
export const RECEIVE_PERMISSION = 'RECEIVE_PERMISSION'